### PR TITLE
fix(email): add better password change link for certain emails

### LINKED ISSUE #78: "New sign-in to Sync" mail has bad advice re ignoring the email if received in error.
The fine-print in the mail says "This is an automated email; if you received it in error, no action is required." - I'm not sure that is good advice as it implies someone has their password.

### PR DESCRIPTION
**Pull request by vladikoff**
Fix #78

### CODE REVIEW

**Comment by vladikoff** [comment]
still wip, 

- need to check if we want this new link to /settings (as suggested in https://github.com/mozilla/fxa-auth-mailer/issues/78)
- need to check if this should be added in other emails besides just the new sync device

**Comment by vladikoff** [comment]
@zaach @rfk r?

File: mailer.js [hunk 1]
```diff
@@ -162,7 +169,8 @@ module.exports = function (log) {
         email: message.email,
         link: link,
         supportUrl: this.supportUrl,
-        supportLinkAttributes: this._supportLinkAttributes()
+        supportLinkAttributes: this._supportLinkAttributes(),
+        passwordChangeUrl: this._initiatePasswordChange()
```
Comment (rfk) [inline mailer.js]: naming nit: `passwordChangeLinkAttributes` or similar for consistency, since it's not just the URL?

File: mailer.js [hunk 2]
```diff
@@ -321,7 +334,8 @@ module.exports = function (log) {
         link: link,
         oneClickLink: oneClickLink,
         supportUrl: this.supportUrl,
-        supportLinkAttributes: this._supportLinkAttributes()
+        supportLinkAttributes: this._supportLinkAttributes(),
+        passwordChangeUrl: this._initiatePasswordChange()
```
Comment (rfk) [inline mailer.js]: Wow that's a lot of identical changes...I wonder if we should factor these links out into some common set of attributes that are included in every render, so that we can manage them in a single place.

**Comment by rfk** [comment]
@vladikoff travis bustage?

**Comment by rfk** [comment]
Also if I understand the rules correctly (thanks to a recent refresher from @shane-tomlinson) then we shouldn't merge this l10n-affecting string change until after we cut the next train...?

**Comment by vladikoff** [comment]
will fix the tests and ping @shane-tomlinson before cutting strings....

**Comment by shane-tomlinson** [comment]
> Also if I understand the rules correctly (thanks to a recent refresher from @shane-tomlinson) then we shouldn't merge this l10n-affecting string change until after we cut the next train...?

We are in the "merge new strings!" window, until I go to sleep tonight.

File: mailer.js (hunk 2 above)
Comment (vladikoff) [inline mailer.js]: opened https://github.com/mozilla/fxa-auth-mailer/issues/94 so we can merge this and cut strings

File: test/local/mailer_tests.js [hunk 3]
```diff
@@ -43,7 +43,7 @@ P.all(
           service: 'service',
         }
 
-        var supportHtmlLink = new RegExp('<a href="' + config.mail.supportUrl + '" style="color: #0095dd; text-decoration: none;">Mozilla Support</a>')
+        var supportHtmlLink = new RegExp('<a href="' + config.mail.supportUrl + '" style="color: #0095dd; text-decoration: none; font-family: sans-serif;">Mozilla Support</a>')
```
Comment (shane-tomlinson) [inline test/local/mailer_tests.js]: Should we add a "Change Password" link test too?

File: templates/password_reset.html [hunk 4]
```diff
@@ -27,7 +27,7 @@ <h1 style="font-family: sans-serif; font-weight: normal; margin: 0 0 24px 0; tex
   <td border="0" cellpadding="0" cellspacing="0" height="100%" width="100%">
     <br/>
     <p class="secondary" style="font-family: sans-serif; font-weight: normal; margin: 0; text-align: center; color: #8A9BA8; font-size: 11px; line-height: 13px; width: 310px !important; word-wrap:break-word">
-      {{t "This is an automated email; if you received it in error, no action is required."}} {{{t "For more information, please visit <a %(supportLinkAttributes)s>Mozilla Support</a>"}}}
+      {{t "This is an automated email; if you did not authorize this action, then <a %(passwordChangeLinkAttributes)s>please change your password.</a>" }} {{{t "For more information, please visit <a %(supportLinkAttributes)s>Mozilla Support</a>"}}}
```
Comment (shane-tomlinson) [inline templates/password_reset.html]: Ahh, since this now has HTML, you'll have to replace `{{` with `{{{`or else the HTML will be escaped.

File: test/local/mailer_tests.js (hunk 3 above)
Comment (vladikoff) [inline test/local/mailer_tests.js]: added to https://github.com/mozilla/fxa-auth-mailer/issues/94

File: templates/password_reset.html (hunk 4 above)
Comment (shane-tomlinson) [inline templates/password_reset.html]: That's my theory anyways.

File: mailer.js [hunk 5]
```diff
@@ -130,7 +136,8 @@ module.exports = function (log) {
         link: link,
         oneClickLink: oneClickLink,
         supportUrl: this.supportUrl,
-        supportLinkAttributes: this._supportLinkAttributes()
+        supportLinkAttributes: this._supportLinkAttributes(),
+        passwordChangeLinkAttributes: this._initiatePasswordChange()
```
Comment (shane-tomlinson) [inline mailer.js]: Should `_initiatePasswordChange` be renamed to `_passwordChangeLinkAttributes` to stay consistent?

File: templates/password_reset.html (hunk 4 above)
Comment (vladikoff) [inline templates/password_reset.html]: yea good note fixed via https://github.com/mozilla/fxa-auth-mailer/commit/83984f6789b8e998a1fea2a3907fa8ab40a9a2bd

File: mailer.js (hunk 5 above)
Comment (vladikoff) [inline mailer.js]: added a note to https://github.com/mozilla/fxa-auth-mailer/issues/94#issuecomment-148462202
